### PR TITLE
[MCOMPILER-488] dedicated option for `implicit` javac flag

### PR DESCRIPTION
**Pull request by pzygielo**
Needs
- https://github.com/codehaus-plexus/plexus-compiler/pull/202

or similar.

- [MCOMPILER-488](https://issues.apache.org/jira/browse/MCOMPILER-488)

### CODE REVIEW

**Comment by olamy** [comment]
@pzygielo plexus-compiler changes merged and 2.11.2-SNAPSHOT so you can mark it as ready ;)

**Comment by pzygielo** [comment]
@olamy - thanks for checking (and pushing `plexus-*`es).
This has now completed GH workflow and is marked as ready for review.

I added [comment](https://issues.apache.org/jira/browse/MCOMPILER-402?focusedCommentId=17507407&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17507407) to MCOMPILER-402 to update [the example](https://maven.apache.org/plugins/maven-compiler-plugin/examples/module-info.html). Not sure about that, and I'd rather not have it in this PR.

**Comment by pzygielo** [comment]
Changed my mind about updating example to _not needed_.

Also - I think it was my mistake to use this ticket. Perhaps it would be better to have new _New feature_ linked to 402. And probably to close 402 as not an issue.

**Comment by olamy** [comment]
> Changed my mind about updating example to _not needed_.
> 
> Also - I think it was my mistake to use this ticket. Perhaps it would be better to have new _New feature_ linked to 402. And probably to close 402 as not an issue.

agree. a new jira as a feature would be nice.

**Comment by pzygielo** [comment]
Switched to new ticket.

**Pull request merged**
