### PR TITLE
MCOMPILER-416 - add skippedKey for check if "Nothing to compile"

### PR DESCRIPTION
**Pull request by qxo**
ie:
when "Nothing to compile" then skip then test1(process-classes)
make the build faster
```
	<plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-compiler-plugin</artifactId>
		<executions>
				<execution>
						<id>default-compile</id>
						<phase>compile</phase>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<skippedKey>nothingToCompileOn</skippedKey>
						</configuration>
				</execution>
		</executions>
	</plugin>
	<plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-antrun-plugin</artifactId>
		<version>3.0.0</version>
		<executions>
		  <execution>
			<id>test1</id>
			<phase>process-classes</phase>
			<configuration>
			  <target>
				<echoproperties>
					<propertyset><propertyref prefix="nothing"/></propertyset>
				</echoproperties>
			  </target>
			  <skip>${nothingToCompileOn}</skip>
			</configuration>
			<goals>
			  <goal>run</goal>
			</goals>
		  </execution>
		</executions>
	</plugin>
```

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MCOMPILER) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MPH-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MPH-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by qxo** [comment]
ref: https://issues.apache.org/jira/browse/MCOMPILER-416

**Comment by rfscholte** [comment]
I'm missing a [ticket in Jira |http://issues.apache.org/jira/browse/MCOMPILER] and a good valid usecase to implement this, because this now looks like a hack.

**Comment by rfscholte** [comment]
Marked as `won't fix` in MCOMPILER-416

**Comment by jira-importer** [comment]
Resolve #639

**Pull request closed without merging**
