### PR TITLE
[MCOMPILER 366] - Warning about automodules should provide the list o…

### PR DESCRIPTION
**Pull request by ofarganc**
…f offending libraries

- Collected filename based automodules detected and added to the log message.
- Updated unit tests accordingly.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MCOMPILER) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[MPH-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MPH-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [X] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by olamy** [comment]
@ofarganc very useful/nice improvement!!! can you improve the test with multiple jars generating the warning?

**Comment by sormuras** [comment]
Looks good to me, too.

I wonder, if we should add a check for invalid "automatic-module-name" entries in all dependencies as well. Similar to the new check performed by the `maven-jar-plugin`/`maven-archiver` ... https://github.com/apache/maven-archiver/pull/1/files

**Comment by rfscholte** [comment]
> I wonder, if we should add a check for invalid "automatic-module-name" entries in all dependencies as well. 
If this project would need them, then the build would fail anyway. I'd prefer to keep these checks at the right place. Keep compiling as clean as possible.
Another reason: consider this plugin as a wrapper around javac. If that executable likes it, so should the plugin.

**Comment by sormuras** [comment]
I agree, @rfscholte

**Comment by ofarganc** [comment]
> @ofarganc very useful/nice improvement!!! can you improve the test with multiple jars generating the warning?

thanks @olamy, I'll give it a try and add it to the PR.

**Comment by khmarbaise** [comment]
CI is looking fine https://builds.apache.org/view/M-R/view/Maven/job/maven-box/job/maven-compiler-plugin/job/MCOMPILER-366/ squashed the commits and merged into master.

**Pull request closed without merging**
