### PR TITLE
[MCOMPILER-517] take into account last compilation time to not recompile even if user has been to install phase

### PR DESCRIPTION
**Pull request by olamy**
https://issues.apache.org/jira/browse/MCOMPILER-517

need this https://github.com/apache/maven-shared-incremental/pull/18

Signed-off-by: Olivier Lamy <olamy@apache.org>

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MCOMPILER) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MCOMPILER-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MCOMPILER-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Review by eolivelli — COMMENTED** [review]
Great stuff!

**Review by gnodet — CHANGES_REQUESTED** [review]
I'm -1 on such a change.  This assumes the compiled classes are the same than the one in the packaged artifact, which I think is wrong.  The shade plugin for example can post-process classes, so storing the compilation time is a bad idea.  
When running multiple `mvn install`, I think the goal is to expect no artifact to be changed at all.  This will  speed up the build much more.

**Comment by olamy** [comment]
yup was a bad idea. anyway my main issue is fixed with the build cache extension

**Comment by jira-importer** [comment]
Resolve #729

**Pull request closed without merging**
