### PR TITLE
Miscellaneous code cleanups

### PR DESCRIPTION
**Pull request by rhowe**
These were the result of running the IntelliJ linter and picking the juiciest looking changes.

Hopefully there's nothing too contentious here - see individual commits for details.

Addresses

- MCOMPILER-382
- MCOMPILER-383
- MCOMPILER-384
- MCOMPILER-385

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Comment by rhowe-gds** [comment]
If you want a Jira ticket for these changes let me know and I'll make one and rewrite the commits

**Comment by khmarbaise** [comment]
Please create some of them...

**Comment by rhowe** [comment]
OK, I made 4 tickets for the 4 classes of change & rewrote the commit messages.
Also I took out the dos->unix line ending change because I didn't end up touching that class in the end.

There are a bunch of DOS format files in the repo - any objection to a PR that converts them all to unix line ending and then leave git to do the right thing for all platforms?

**Comment by rhowe-gds** [comment]
@eolivelli sorry for the nudge - how's this change looking?

**Comment by eolivelli** [comment]
> @eolivelli sorry for the nudge - how's this change looking?

It looks great !

**Pull request merged**
