### PR TITLE
[MCOMPILER-457] Warn about warn-config conflicting values

### PR DESCRIPTION
**Pull request by pzygielo**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MCOMPILER) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MCOMPILER-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MCOMPILER-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by pzygielo** [comment]
May I ask for review, please?

**Comment by slawekjaranowski** [comment]
Does this PR resolve issue?
As I understood setting only `failOnWarning` to `true` has no efect.
Maybe when `failOnWarning` is `true` we also need to change `showWarnings` to `true`.

**Comment by pzygielo** [comment]
I didn't want to change currently implemented logic.
MCOMPILER-457 happened to me as well. Caused some... confusion.

For future me, that does not remember that, it'd be fine to be warned about strange plugin set up.

> Maybe when `failOnWarning` is true we also need to change `showWarnings` to true.

Maybe. I'd like to have the warning at least in such case as well, that parameter is updated out of my control.

**Comment by pzygielo** [comment]
Is there any change requested here?

**Comment by olamy** [comment]
maybe we should simply change `showWarnings` to `true` per default as described in MCOMPILER-457?

**Comment by pzygielo** [comment]
> maybe we should simply change `showWarnings` to `true` per default as described in MCOMPILER-457?

- Doing so in apache/maven-compiler-plugin#157
- What about THIS change?

**Comment by pzygielo** [comment]
May I ask for review, please?

**Comment by jira-importer** [comment]
Resolve #683

**Pull request merged**
