### PR TITLE
MCOMPILER-359 - Fix for NPE

### PR DESCRIPTION
**Pull request by hohwille**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [MCOMPILER-359](https://issues.apache.org/jira/browse/MCOMPILER-359) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MPH-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MPH-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why: `pathException.getValue().getCause()` may already be null
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically. - I expect you to have a CI setup (e.g. travis)
 - [ ] You have run the integration tests successfully (`mvn -Prun-its clean verify`). - I expect you to have a CI setup (e.g. travis).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by hohwille** [comment]
Indeed no CI present - Incredible. I thought the ASF would be more sophisticated than my personal OSS projects...

**Comment by rfscholte** [comment]
No need to worry, https://builds.apache.org/job/maven-box/job/maven-compiler-plugin/job/master/

**Comment by rfscholte** [comment]
Can you expand the integrationtest of src/it/MCOMPILER-360 ?

**Comment by hohwille** [comment]
good to know that CI is present. Thanks for the link. You can even integrate Jenkins with github, though...

> Can you expand the integrationtest of src/it/MCOMPILER-360 ?

To be honest. I do not know how. My problem is that I would like to figure out the actual exception that was caused. Due to this NPE that is triggered instead, I am unable to see what is going wrong as the important stacktrace is finally lost. As I can only reproduce the error in travis-ci and not locally, I am completely lost. Here is my travis log:
https://api.travis-ci.org/v3/job/626312654/log.txt

I would be awesome to figure out what is really going wrong. However, I fear that it will take ages till a new version of maven-compiler-plugin is released where the NPE is fixed (no offence, we are all very busy coders - I myself also would urgendly need to implement various fixes for flatten-maven-plugin but can not find the time) and I have upgraded to that version so I can see what the actual error is. Any idea how to speed up this analysis?

**Comment by sormuras** [comment]
This is line that yields the NPE:
https://github.com/apache/maven-compiler-plugin/blob/maven-compiler-plugin-3.8.1/src/main/java/org/apache/maven/plugin/compiler/TestCompilerMojo.java#L254

The initial value assigned "cause" is tested for being "null":

253:                    Throwable cause =
pathException.getValue().getCause();
254:                    while ( cause.getCause() != null )
255:                    {
256:                        cause = cause.getCause();
257:                    }

Current master branch doesn't differ, i.e. it also will throw a NPE.

Robert: Should the initial cause of a "path exception value" always be
assigned?
If not, just report the path exception without the message pointing to the
cause?

**Comment by jira-importer** [comment]
Resolve #575

**Pull request merged**
