### PR TITLE
[MCOMPILER-404] Update default source/target from 1.6 to 1.7

### PR DESCRIPTION
**Pull request by turbanoff**
- [*] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Comment by michael-o** [comment]
We should change it to 7 instead of 1.7 in my opinion.

**Comment by rfscholte** [comment]
How about keeping the 1.N for source/target to give users the feeling they're still using an old version and reserve the N version when talking about {{release}}. Hopefully people start recognizing this new release flag much easier.

**Comment by turbanoff** [comment]
> We should change it to 7 instead of 1.7 in my opinion.
From my point of view 1.7 is less risky choice. I think there are set of tools which will work with `1.7`, but will fail with `7`.

**Comment by rfscholte** [comment]
Fixed in https://github.com/apache/maven-compiler-plugin/commit/dc4a5635ba4eb2ba5e461fa53b2c47c58d7fa397

**Comment by jira-importer** [comment]
Resolve #632

**Pull request closed without merging**
