### PR TITLE
Remove unused private field

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by michael-o** [comment]
This may  be a bug, no?

**Comment by pzygielo** [comment]
> This may be a bug, no?

I'm not sure what you mean by that.

**Comment by michael-o** [comment]
> 
> 
> > This may be a bug, no?
> 
> I'm not sure what you mean by that.

Obviously, not the empty list should be passed. This case could either be what you say or simply a bug that `compilePath` is not passed down to the test.

**Comment by pzygielo** [comment]
`compilePath` is unused field in `TestCompilerMojo`. That field is removed and then change in test that sets non-existent field follows.

**Comment by pzygielo** [comment]
What can I do to move it forward?

**Review by rfscholte — APPROVED** [review]
Looking at the git-blame it seems I introduced it for MCOMPILER-269 but might have become obsolete with MCOMPILER-341.
I do remember that is was required to know which of the dependencies were added for testing purpose.
Knowing that all modulepath related tickets have a test, it should be safe to remove this unused field.

**Comment by pzygielo** [comment]
What can I do to move it forward even more?

**Comment by rfscholte** [comment]
Merged with https://github.com/apache/maven-compiler-plugin/commit/419bf040893dac8f300deb5b36daf5f487dea8d2

**Pull request closed without merging**
