### PR TITLE
[MCOMPILER-544] don't add items to classpath that are not used for that

### PR DESCRIPTION
**Pull request by laeubi**
Currently simply all kind of items are added to the classpath leading to strange errors in the ECJ compiler plugin because it does not know how to handle pom or other possible types.

This adds an additional check to see if the artifact handler actually claims the itme should be put on the classpath,

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MCOMPILER-544) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MCOMPILER-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MCOMPILER-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Review by gnodet — APPROVED** [review]
LGTM

**Comment by slawekjaranowski** [comment]
Cen we add example from jira as IT?

**Comment by laeubi** [comment]
> Cen we add example from jira as IT?

I'm not that familiar with compiler-itests but it should be enough to check that no ERROR printout is there when executing the given pom example on a project that has at least one dummy source file so compilation is triggered...

**Comment by laeubi** [comment]
@slawekjaranowski can you help with the test-case here? I anything else needed or does it look sane?

**Pull request merged**
